### ISSUE TITLE
how to convert voxel to triangle mesh

### ISSUE THREAD

**Issue by Xianjin111** [davidstutz/mesh-voxelization#11]
Hi!

Thank you for your perfect work. I have a question that is there any way to turn the voxel into a triangle mesh?

Thank you very much.

**Comment by davidstutz** [comment]
You can have a look at marching cubes, for example https://github.com/pmneila/PyMCubes.

**Comment by davidstutz** [comment]
Short update: in this case you should use SDFs instead of binary voxel grids.
