### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by christinazavou** [davidstutz/mesh-voxelization#12]
Hi,

is there any plan on adding color to the voxels? Do you know of any library that generates voxels with color info?

thanks!

**Comment by davidstutz** [comment]
No there is not plan to extend this to colors. I am also not aware of any library for doing this, but have not been working with meshes/voxel grids for a while.

I do think, however, that it should be quite easy to extend it yourself to colors. Check out https://github.com/davidstutz/mesh-voxelization/blob/91c2d08175862ff011c166b756c84e1049ff267d/main.cpp#L351: when iterating over the faces, you could load additional color information of the faces in the from_off method and then just fill an additional rank-3 tensor (in addition to the occ tensor) with the color information.
