### ISSUE TITLE
fill_occupancy.py.sofa in and A big cube is created??

### ISSUE THREAD

**Issue by York1996OutLook** [davidstutz/mesh-voxelization#2]
Whatever you put in, it's going to produce a cube.the filled.h5 file tensor is Most of them are 1.(>99%)

**Comment by York1996OutLook** [comment]
because of i didnt run scale first

**Comment by davidstutz** [comment]
Sorry for the late answer. Did you use one of the provided examples? If not, did you make sure that your input mesh is watertight? If a cube is created, meaning the whole space is voxelized, this might mean that your mesh is not watertight (not clear inside and outside).
