### ISSUE TITLE
the file name should be all numbers???????

### ISSUE THREAD

**Issue by York1996OutLook** [davidstutz/mesh-voxelization#3]
../bin/voxelize occ ../examples/input ../examples/output.h5
i found that when filename like "a.off",failed ,invaild augument..............
It looks like it only supports naming files with Numbers

**Comment by davidstutz** [comment]
Yes, as documented in the README and using `--help`, only numbered files are supported:

    --input arg    input, either single OFF file or directory containing 
                        OFF files where the names correspond to integers (zero 
                        padding allowed) and are consecutively numbered 
                        starting with zero
