### ISSUE TITLE
12311File,1.6GB occ.h5 file,but tensor with size(5,32,32,32)????

### ISSUE THREAD

**Issue by York1996OutLook** [davidstutz/mesh-voxelization#4]
The magnitude of the tensor should be(12311,32,32,32).
but got (5,32,32,32),and the h5 file has size 1.6GB.
its wired...
do you know why?

**Comment by davidstutz** [comment]
Seems like the tool did not find all your input mesh files. Did you check that all of them have consecutive numbering? A file size of 1.6GB for 5 32x32x32 voxelized meshes sounds weird.

Can you give more details on your input and how you call the tool?

**Comment by York1996OutLook** [comment]
the file size is big (1.6GB)，but tensor is small,i dont know why.
and I've forgotten the details

**Comment by davidstutz** [comment]
Are you sure you are reading it right and checking the right size. Maybe you are only reasing a chunk of the HDF4 file. Reopen if problem still persists.
