### ISSUE TITLE
Only positive sdf values when processing the models of ShapeNet 

### ISSUE THREAD

**Issue by Edwinzero** [davidstutz/mesh-voxelization#5]
Hi  @davidstutz ,

I am using this mesh-voxelization script to generate SDF volume with the ShapeNet dataset.
The model I tested is a watertight sofa model, but the result shows there is no interior value generated. 
The value of the num_intersect variable is always even number.
Could you give me some suggestions or help in solving this weird situation?
Thank you very much for considering this matter.

The model I am using for testing is 
ShapeNetCore.v2\\ 04256520 \\ 1037fd31d12178d396f164a988ef37cc \\ models \\ model_normalized.obj

**Comment by davidstutz** [comment]
Are you sure the model is entirely watertight? If you are using a model from ShapeNet without any pre-processing this is very unlikely.

Also, did you check which values were generated? For example, the model might not be normalized to `[0, H] x [0, W] x [0, D]` with `H x W x D` being the size of the voxelized version.
