### ISSUE TITLE
[Question] Is there anyway to `fill` a water-tight voxel grid?

### ISSUE THREAD

**Issue by ElectronicElephant** [davidstutz/mesh-voxelization#7]
Hello!

First, thank you for your awesome job!

Currently I'm working on the auto-encoders of 3D voxels. As you have said,

> Note that these are not "filled"; meaning that only the mesh surfaces are voxelized. 

many datasets provide voxels that contain only the surfaces, leaving the **inner** part hollow. This make it very difficult for auto-encoders to catch the **surfaces**, since the surfaces are only 1-grid-thick. I hope some tools can help me to fill them automatically.

My question is that, is `filling the inner part of a water-tight voxel` still an open-question? Is there any good idea to do it automatically?

Thanks.

**Comment by ElectronicElephant** [comment]
Okay, I find that 

> Assuming the original shapes to be mostly watertight, the occupancy grids can be filled using a connected components algorithm as in examples/fill_occupancy.py

I will first try it and close the issue up to now. Thanks. I was just too hurried.

**Comment by davidstutz** [comment]
No, filling in is not a big problem using simple connected components algorithms in 3D. But you need themesh to be watertight.
