### ISSUE TITLE
`error.printError()` not found.

### ISSUE THREAD

**Issue by bchao1** [davidstutz/mesh-voxelization#8]
When building the repo, I encountered several errors with the following error message:

` ‘class H5::FileIException’ has no member named ‘printError’; did you mean ‘printErrorStack’? `

After tracing the code, I found that in `read_hd5.cpp` and `main.cpp`, there are calls to the `printError` function, which turns out should be `printErrorStack`. I fixed this locally and was able to build the executable. Maybe you want to update the repo to fix this issue.

**Comment by davidstutz** [comment]
Ok, weird. According to documentation and my memory, there should be a printError function (https://support.hdfgroup.org/HDF5/doc/cpplus_RM/class_h5_1_1_exception.html#ad5bf0f93b4156d6366110dd5e08342a2).

**Comment by julianschoep** [comment]
I ran into the same issue. @bchao1's suggestion worked for me.

**Comment by davidstutz** [comment]
Fixed it.
